# -*- coding: utf-8 -*-
import pandas as pd

_col_map = {
    'IDX_NM': '지수명',
    'IDX_IND_NM': '지수명',
    'IDX_ENG_NM': '지수영문명',
    'BAS_DD': '일자',
    'BAS_TM_CONTN': '기준일',
    'ANNC_TM_CONTN': '발표일',
    'BAS_IDX_CONTN': '기준지수',
    'CALC_CYCLE_CONTN': '산출지수',
    'CALC_TM_CONTN': '산출시간',
    'COMPST_ISU_CNT': '구성족목수',
    'ISU_SRT_CD': '종목코드',
    'ISU_ABBRV': '종목명',
    'IDX_EN_NM': '영문지수',
    'OPN_DD_INDX': '시작일기준',
    'END_DD_INDX': '종료일기준',
    'TRD_DD': '일자',
    'CLSPRC_IDX': '종가',
    'TDD_CLSPRC': '종가',
    'FLUC_TP_CD1': '총수익증감',
    'FLUC_TP_CD2': '순가격증감',
    'FLUC_TP_CD3': '제로투자증감',
    'FLUC_TP_CD4': '콜재투증감',
    'FLUC_TP_CD5': '시장가격증감',
    'FLUC_TP_CD': '증감',
    'CMPPREVDD_IDX': '대비',
    'CMPPREVDD_IDX1': '총수익대비',
    'CMPPREVDD_IDX2': '순가격대비',
    'CMPPREVDD_IDX3': '제로투자대비',
    'CMPPREVDD_IDX4': '콜재투자대비',
    'CMPPREVDD_IDX5': '시장가격대비',
    'FLUC_TP': '대비',
    'PRV_DD_CMPR': '대비',
    'STR_CMP_PRC' : '대비',
    'UPDN_RATE': '등락률',
    'FLUC_RT': '등락률',
    'OPNPRC_IDX': '시가',
    'HGPRC_IDX': '고가',
    'LWPRC_IDX': '저가',
    'ACC_TRDVOL': '거래량',
    'ACC_TRDVAL': '거래대금',
    'MKTCAP': '상장시가총액',
    'WT_PER': 'PER',
    'WT_STKPRC_NETASST_RTO': 'PBR',
    'DIV_YD': '배당수익률',
    'BND_IDX_GRP_NM': '지수명',
    'TOT_EARNG_IDX': '총수익종가',
    'TOT_EARNG_IDX_FLUC_TP': '총수익증감',
    'TOT_EARNG_IDX_CMPPREVDD': '총수익대비',
    'NETPRC_IDX': '순가격종가',
    'NETPRC_IDX_FLUC_TP': '순가격증감',
    'NETPRC_IDX_CMPPREVDD': '순가격대비',
    'ZERO_REINVST_IDX': '제로재투자종가',
    'ZERO_REINVST_IDX_FLUC_TP': '제로재투자증감',
    'ZERO_REINVST_IDX_CMPPREVDD': '제재투자대비',
    'CALL_REINVST_IDX': '콜재투자지수',
    'CALL_REINVST_IDX_FLUC_TP': '콜재투자증감',
    'CALL_REINVST_IDX_CMPPREVDD': '콜재투대비',
    'MKT_PRC_IDX': '시장가격지수',
    'MKT_PRC_IDX_FLUC_TP': '시장가격증감',
    'MKT_PRC_IDX_CMPPREVDD': '시장가격대비',
    'AVG_DURATION': '듀레이션',
    'AVG_CONVEXITY_PRC': '컨벡시티',
    'BND_IDX_AVG_YD': 'YTM',
    'MKT_NM': '시장구분',
    'SECT_TP_NM': '소속부',
    'CMPPREVDD_PRC': '대비',
    'TDD_OPNPRC': '시가',
    'TDD_HGPRC': '고가',
    'TDD_LWPRC': '저가',
    'LIST_SHRS': '상장주식수',
    'BAS_PRC': '시작일기준가',
    'MMEND_CLSPRC': '종가',
    'HGST_CLSPRC': '최고종가',
    'LWST_CLSPRC': '최저종가',
    'MM_ACC_TRDVOL': '총거래량',
    'AVG_ACC_TRDVOL': '일평균거래량',
    'MM_ACC_TRDVAL': '총거래대금',
    'AVG_ACC_TRDVAL': '일평균거래대금',
    'ISU_CD': '표준종목코드',
    'ISU_NM': '한글종목명',
    'ISU_ENG_NM': '영문종목명',
    'LIST_DD': '상장일',
    'MKT_TP_NM': '시장구분',
    'SECUGRP_NM': '증권구분',
    'KIND_STKCERT_TP_NM': '주식종류',
    'PARVAL': '액면가',
    'HALT_YN': '매매거래정지',
    'ARRANTRD_YN': '정리매매종목',
    'ADMISU_YN': '관리종목',
    'INVSTCAUTN_REMND_ISU_YN': '투자주의환기',
    'NFAITHDISCLS_YN': '불성실공시',
    'VLWLIQU_VALU_YN': '단일가매매대상초저유동성종목',
    'UNIT_TRD_YN': '상장주식수부족우선주',
    'SRTTRM_OVERHEAT_ISU_TP_YN': '단기과열종목',
    'INVSTCAUTN_YN': '투자주의종목',
    'NVST_WARN_YN': '투자경고종목',
    'NVST_RISK_YN': '투자위험종목',
    'INVST_TP_NM': '투자자구분',
    'ASK_TRDVOL': '매도거래량',
    'BID_TRDVOL': '매수거래량',
    'NETBID_TRDVOL': '순매수거래량',
    'ASK_TRDVAL': '매도거래대금',
    'BID_TRDVAL': '매수거래대금',
    'NETBID_TRDVAL': '순매수거래대금',
    'TRDVAL1': '기관합계/금융투자(d)',
    'TRDVAL2': '기타법인/보험(d)',
    'TRDVAL3': '개인/투신(d)',
    'TRDVAL4': '외국인/사모(d)',
    'TRDVAL5': '은행',
    'TRDVAL6': '기타금융',
    'TRDVAL7': '연기금 등',
    'TRDVAL8': '기타법인',
    'TRDVAL9': '개인',
    'TRDVAL10': '외국인',
    'TRDVAL11': '기타외국인',
    'TRDVAL_TOT': '전체',
    'CMPPRVDD_PRC': '대비',
    'BLK_TRDVOL': '대량매매수량',
    'BLK_TRD_RTO': '대량매매비율',
    'ITM_TP_NM': '구분',
    'EXST_STRT_DD': '존립기간시작일',
    'EXST_END_DD': '존립기간종료일',
    'EXER_PRC': '행사가격',
    'TARSTK_ISU_SRT_CD': '목적주권-종목코드',
    'TARSTK_ISU_NM': '목적주권-종목명',
    'TARSTK_ISU_PRSNT_PRC': '목적주권-종가',
    'ISU_PRC': '신주발행가',
    'DELIST_DD': '상장폐지일',
    'DPS': '주당배당금',
    'DVD_YLD': '배당수익률',
    'BPS': 'BPS',
    'PER': 'PER',
    'EPS': 'EPS',
    'PBR': 'PBR',
    'FORN_HD_MKTCAP': '외국인보유총액',
    'MKTCAP_RTO': '시가총액비율',
    'FORN_HD_SHRS': '외국인보유주식수',
    'LIST_SHRS_RTO': '주식수비율',
    'FORN_HD_QTY': '외국인보유수량',
    'FORN_SHR_RT': '외국인지분율',
    'FORN_ORD_LMT_QTY': '외국인한도수량',
    'FORN_LMT_EXHST_RT': '외국인한도소진율',
    'LISTCOM_CNT': '회사수',
    'LIST_ISU_CNT': '종목수',
    'MKTCAP_RT': '시가총액비중',
    'ACC_TRDVOL_RT': '거래량비중',
    'ACC_TRDVAL_RT': '거래대금비',
    'SB_PRC': '대용가격',
    'MK_DATE': '산출기준일',
    'PREVDD_CLSPRC': '산출기준일 종가',
    "ASSTCOM_NM": '회사명',
    "ASSTCOM_FND_NM": '종목명',
    "STRT_DD": '시작일',
    "END_DD": '종료일',
    'INVSTASST_NETASST_TOTAMT': '순자산총액',
    'NAV': '순자산가치',
    'OBJ_STKPRC_IDX': '종가',
    'FLUC_RT1': '등락률',
    'CMP_PRC': '대비',
    'CLSPRC': '종료일 종가',
    'LST_NAV': '순자산가치',
    'IDX_FLUC_RT': '등락률',
    'ETF_OBJ_IDX_NM': '기초지수명',
    'IDX_CALC_INST_NM1': '지수산출기관',
    'IDX_CALC_INST_NM2': '추적배수',
    'ETF_REPLICA_METHD_TP_CD': '복제방법',
    'IDX_MKT_CLSS_NM': '기초시장분류',
    'IDX_ASST_CLSS_NM':	'기초자산분',
    'COM_ABBRV': '운용사',
    'CU_QTY': 'CU수량',
    'ETF_TOT_FEE': '홍보수',
    'TAX_TP_CD': '과세유형',
    'NUM_ITM_VAL21': '기간 합계',
    'NUM_ITM_VAL22': '기간법인',
    'NUM_ITM_VAL23': '개인',
    'NUM_ITM_VAL24': '외국인 합계',
    'NUM_ITM_VAL25': '전체',
    'INVST_NM': '투자자 구분',
    'COMPST_ISU_CD': '종목코드',
    'COMPST_ISU_NM': '종목명',
    'COMPST_ISU_CU1_SHRS': '주식',
    'VALU_AMT': '평가금액',
    'COMPST_AMT': '시가총액',
    'COMPST_RTO': '시가총액기준구성비중',
    'CLSPRC1': '비교지수종가 시작일',
    'BAS_IDX1': '비교지수종가 종료일',
    'CLSPRC2': 'ETF종가 시작일',
    'BAS_IDX2': 'ETF종가 종료',
    'DISTR_AMT': '누적 분배금',
    'NAV_CHG_RT': '순자산가치(NAV)변동률',
    'IDX_CHG_RTO': '기초지수',
    'DIVRG_RT': '장마감 괴리율',
    'TRD_REL_MBR_NM': '거래상대방명',
    'OTC_DRV_CLSS_FND_GIV_TP_NM': '장외파생상품 유형',
    'ETF_NETASST_TOTAMT': '순자산총액(a)',
    'ETF_TOT_RISK_EXPOSR_AMT': '총위험노출액(b)',
    'ETF_COLTRL_VALU_AMT': '담보평가액(c)',
    'ETF_COLTRL_RTO': '담보비율(c/b)',
    'ETF_RISK_VALU_AMT': '위험평가액(d=b-c)',
    'ETF_RISK_VALU_AMT_RTO': '위험평가액비율(d/a)',
    'MKTCLS_NAV': '장마감 순자산가치(NAV)',
    'CLSPRC_DIVRG_RT': '장마감 괴리',
    'ISU_KOR_ABBRV': '종목명',
    'SYNTH_ETF_BAS_IDX_OVRVW': '지수산출내역',
    'SYNTH_ETF_COLTRL_ADM_OVRVW': '담보관리정책',
    'BAS_IDX_REL_ASSTCOM_HPAGE_ADDR': '지수산출내역링크',
    'COLTRL_ADM_ASSTCOM_HPAGE_ADDR': '담보관리정책',
    'TRACE_YD_MULT': '추적수익률 배수',
    'TRACE_ERR_RT': '추적오차율',
    'PER1SECU_INDIC_VAL': '지표가치(IV)',
    'INDIC_VAL_AMT': '지표가치총액',
    'COMP_PRC': '대비',
    'LSTTRD_DD': '최종거래일',
    'TRACE_IDX_NM': '기초지수명',
    'IDX_CALC_INST_NM': '지수산출기관',
    'IDX_LVRG_INVRS_TP_CD': '추적배수',
    'ETP_PROD_TP_CD': '상품구분',
    'ISUR_NM': '발행사',
    'EXPS_RTO': '총보수',
    'CREDIT_GRD_CONTN': '최근신용등급_1',
    'CREDIT_VALU_INST_NM': '최근신용평가회사_1',
    'CREDIT_GRD_CHG_DD': '변경일_1',
    'CREDIT_GRD_CONTN2': '최근신용등급_2',
    'CREDIT_VALU_INST_NM2': '최근신용평가회사_2',
    'CREDIT_GRD_CHG_DD2': '변경일_2',
    'NUM_RTO': 'NCR 기준월말(8월)',
    'NUM_RTO1': 'NCR 기준월 전월말',
    'NUM_RTO2': 'NCR 기준원 전전월말',
    'AGG_VAL': '합계',
    'EQTYCAP': '자기자본금액',
    'EQTYCAP_RTO': '자기자본비율',
    'CREDIT_GRD': '신용등급',
    'NCR': 'NCR',
    'LOSS_LMT_ETN_EARNG_STRUCT_NM': '수익구조유형',
    'ETN_EARY_REDMPT_CYCLE_CD_NM': '조기상환주기',
    'STR_CONST_VAL': '조기상환조건 차수',
    'EARY_REDMPT_VALU_DD': '조기상환조건 평가일',
    'EARY_REDMPT_COND_REL_CD': '조기상환조건기준',
    'EARY_REDMPT_PRC': '조기상환가격(제비용차감젙)',
    'DIFF_PRC': '차이',
    'CMP_RTO2': '버퍼',
    'ULY_NM': '기초자산명',
    'ULY_PRC': '기초자산종가',
    'ULY_CLSPRC': '기초자산종가',
    'EXP_DD': '만기일',
    'ELW_ULY_TP_NM': '기초자산구분',
    'ELW_CONV_RTO': '전환비율',
    'RGHT_TP_NM': '권리유형',
    'ELW_EXER_TP': '권리행사방식',
    'LP_NM': 'LP',
    'ORD_SPD_RTO': '최대호가스프레드비율',
    'ELW_LST_SETL_METHD': '결제방식',
    'ELW_ULY_TP_CD': '기초자산구분',
    'ISU_CNT': '전체종목수',
    'TRDVOL': '전체거래량',
    'TRDVAL': '전체거래대금',
    'ELW_LSTTRD_DD': '최종거래일',
    'REMAIN_EXP_DYS': '잔존만기(만기일-조회일)',
    'EXER_STRT_DD': '권리행사일',
    'ULY_BAS_PRC': '기초자산가격',
    'ELW_EXER_PRC': '행사가격',
    'PARITY_VAL': '패리티',
    'MKTPARTC_ABBRV': 'LP명',
    'LP_HD_QTY': 'LP 보유수량',
    'LP_HD_RT': 'LP 보유비율',
    'EXP_VALU_PRC': '만기평가가격',
    'LP_MBR_NM': 'LP명',
    'ELW_PAY_DD': '지급일',
    'ELW_RGHT_TP': 'CALL/PUT',
    'BND_EXP_TP_NM': '만기년수',
    'GOVBND_ISU_TP_NM': '종목구분',
    'CLSPRC_YD': '종가 수익률',
    'OPNPRC': '시가',
    'OPNPRC_YD': '시가 수익률',
    'HGPRC': '고가',
    'HGPRC_YD': '고가 수익률',
    'LWPRC': '저가',
    'LWPRC_YD': '저가 수익률',

    'BND_CLSS_NM1': '구분1',  # <- row map
    'BND_CLSS_NM2': '구분2',  # <- row map

}


def convert(data, new_col_map):
    global _col_map
    col_map = _col_map.copy()
    if new_col_map:
        col_map = adjust_new_col_map(col_map, new_col_map)
    converted = []
    not_in_map = set()  # delete later
    ignored = set()  # delete later
    key = list(data.keys())[0]
    for d in data[key]:
        column_in_kor = {}
        for k, v in d.items():
            try:
                column_in_kor[col_map[k]] = v
                # column_in_kor[k] = v  # In order to check origin column name
            except:
                if k in ['IND_TP_CD', 'IDX_IND_CD', 'MKT_ID', 'CONV_OBJ_TP_CD', 'ISU_ABBRV_STR', 'ETF_ISU_CD', 'BND_CLSS_CD', 'NUSUAL_ISU_COND_CONTN']:
                    ignored.add(k)
                    continue
                column_in_kor[k] = v
                not_in_map.add(k)  # delete try except no need to use
        converted.append(column_in_kor)
    if len(not_in_map) > 0:
        print(not_in_map)
    if len(ignored) > 0:
        print('ignored : ', ignored)
    return pd.json_normalize(converted)


def adjust_new_col_map(col_map, new_col_map):
    for key, val in new_col_map.items():
        col_map[key] = val
    return col_map
    

